<a href="https://colab.research.google.com/github/AwadZafar5493/Pytorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [4]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Longhand i.e function
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
 #subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [9]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Remainder Modulus
tensor_b % tensor_a


tensor([0, 0, 1, 0])

In [16]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [18]:
#Exponents / Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [19]:
# Reassignment
tensor_a = tensor_a + tensor_b

In [20]:
tensor_a

tensor([ 6,  8, 10, 12])